name: Master - CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: 0 23 * * 1-5

jobs:
    # Windows
    build-windows:
      uses: ./.github/workflows/windows.yml
      with:
        cmake-version: '3.31.0'
        platforms: "['x64', 'Win32', 'ARM64']"
        configurations: "['RelWithDebInfo', 'Debug']"
    # MacOS
    build-macos:
      uses: ./.github/workflows/macos.yml
      with:
        cmake-version: '3.31.0'
        platforms: "['macOS']"
        configurations: "['RelWithDebInfo', 'Debug']"
    # iOS
    build-ios:
      uses: ./.github/workflows/ios.yml
      with:
        cmake-version: '3.31.0'
        platforms: "['iOS']"
        configurations: "['RelWithDebInfo', 'Debug']"
    # Linux
    build-linux:
      uses: ./.github/workflows/linux.yml
      with:
        cmake-version: '3.31.0'
        platforms: "['Linux']"
        configurations: "['RelWithDebInfo', 'Debug']"